services:
  web:
    build: . # QUAN TRỌNG: Bảo Docker dùng Dockerfile trong thư mục này để build
    container_name: web_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules # Giữ lại node_modules đã cài lúc build
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: Hoang182006.
      DATABASE_NAME: mydatabase
      CHOKIDAR_USEPOLLING: "true" # Giúp Next.js hot-reload mượt hơn trên Docker
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hoang182006.
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
